# Generated by Django 6.0.5 on 2026-05-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageStrategySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removal_strategy', models.CharField(choices=[('FIFO', 'FIFO - Ältestes zuerst'), ('LIFO', 'LIFO - Neuestes zuerst'), ('FEFO', 'FEFO - Kürzestes MHD zuerst'), ('HIFO', 'HIFO - Höchster Preis zuerst'), ('LOFO', 'LOFO - Niedrigster Preis zuerst')], default='FIFO', max_length=20)),
                ('putaway_strategy', models.CharField(choices=[('FIXED_BIN', 'Festplatz'), ('EMPTY_BIN', 'Leerplatzsuche'), ('ADD_TO_STOCK', 'Zulagerung')], default='EMPTY_BIN', max_length=30)),
                ('capacity_check_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='fixed_storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_products', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='product',
            name='putaway_strategy',
            field=models.CharField(choices=[('FIXED_BIN', 'Festplatz'), ('EMPTY_BIN', 'Leerplatzsuche'), ('ADD_TO_STOCK', 'Zulagerung')], default='EMPTY_BIN', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='removal_strategy',
            field=models.CharField(choices=[('FIFO', 'FIFO - Ältestes zuerst'), ('LIFO', 'LIFO - Neuestes zuerst'), ('FEFO', 'FEFO - Kürzestes MHD zuerst'), ('HIFO', 'HIFO - Höchster Preis zuerst'), ('LOFO', 'LOFO - Niedrigster Preis zuerst')], default='FIFO', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.packagingtype'),
        ),
    ]
