# Generated by Django 6.0.5 on 2026-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_packagingtype_storagestrategysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='allow_mixed_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='is_empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='max_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
