# Generated by Django 6.0.5 on 2026-06-01 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_storagelocation_allow_mixed_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.storagelocation'),
        ),
    ]
