# Generated by Django 6.0.5 on 2026-06-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stockmovement_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
