# Generated by Django 6.0.5 on 2026-06-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_packagingtype_description_packagingtype_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingtype',
            name='category',
            field=models.CharField(choices=[('PACKAGING', 'Verpackung'), ('LOAD_CARRIER', 'Ladungsträger')], default='PACKAGING', max_length=30),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
