# Generated by Django 6.0.5 on 2026-06-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_packagingtype_category_packagingtype_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='load_carrier_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_carrier_movements', to='inventory.packagingtype'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='packaging_cost_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='packaging_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='packaging_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_movements', to='inventory.packagingtype'),
        ),
    ]
