# Generated by Django 6.0.5 on 2026-06-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stockmovement_load_carrier_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Produktgewicht pro Einheit in kg', max_digits=10, null=True),
        ),
    ]
