# Generated by Django 6.0.5 on 2026-06-09 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_product_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('packaging_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('load_carrier_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_load_carrier_stocks', to='inventory.packagingtype')),
                ('packaging_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_packaging_stocks', to='inventory.packagingtype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_stocks', to='inventory.product')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_positions', to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['storage_location__code', 'product__name'],
                'unique_together': {('product', 'storage_location', 'packaging_type', 'load_carrier_type')},
            },
        ),
    ]
