# Generated by Django 6.0.5 on 2026-06-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_storagelocationstock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storagelocationstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Einstandspreis pro Stück', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storagelocationstock',
            name='unit_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Einstandspreis pro Stück', max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='storagelocationstock',
            unique_together={('product', 'storage_location', 'packaging_type', 'load_carrier_type', 'unit_purchase_price')},
        ),
    ]
