# Generated by Django 6.0.5 on 2026-06-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_storagelocationstock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storagelocationstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='MHD oder Ablaufdatum', null=True),
        ),
        migrations.AddField(
            model_name='storagelocationstock',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='MHD oder Ablaufdatum', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='storagelocationstock',
            unique_together={('product', 'storage_location', 'packaging_type', 'load_carrier_type', 'unit_purchase_price', 'expiry_date')},
        ),
    ]
