# Generated by Django 6.0.5 on 2026-07-07 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_purchaseorder_purchaseorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_order_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Transportauftrag')),
                ('transport_slip_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Transportschein')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Menge')),
                ('status', models.CharField(choices=[('CREATED', 'Erstellt'), ('ASSIGNED', 'Zugewiesen'), ('PICKED', 'Ware aufgenommen'), ('IN_TRANSIT', 'In Transport'), ('COMPLETED', 'Abgeschlossen'), ('CANCELLED', 'Storniert'), ('ERROR', 'Fehler')], default='CREATED', max_length=20, verbose_name='Status')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Referenz')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priorität')),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_scan_value', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transport_orders', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transport_orders', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_orders', to='inventory.product', verbose_name='Produkt')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_orders_source', to='inventory.storagelocation', verbose_name='Quellplatz')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_orders_target', to='inventory.storagelocation', verbose_name='Zielplatz / Bereitstellplatz')),
            ],
            options={
                'verbose_name': 'Transportauftrag',
                'verbose_name_plural': 'Transportaufträge',
                'ordering': ['-created_at'],
            },
        ),
    ]
