# Generated by Django 6.0.5 on 2026-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_transport_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lager', 'Lager'), ('einkauf', 'Einkauf'), ('dispo', 'Dispo'), ('stapler', 'Stapler-Terminal'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
