# Generated by Django 6.0.5 on 2026-07-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_forklift_terminal_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocation',
            name='location_type',
            field=models.CharField(choices=[('RECEIVING', 'Wareneingangsfläche'), ('STORAGE', 'Lagerplatz'), ('SHIPPING', 'Warenausgang / Bereitstellung'), ('QUALITY', 'Prüfung / Klärung'), ('BLOCKED', 'Sperrfläche')], default='STORAGE', max_length=20, verbose_name='Lagerplatztyp'),
        ),
    ]
