# Generated by Django 6.0.5 on 2026-08-28 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_classify_storage_location_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Versandauftrag')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('RELEASED', 'Freigegeben'), ('IN_PICKING', 'In Kommissionierung'), ('READY_FOR_SHIPPING', 'Versandbereit'), ('SHIPPED', 'Versendet'), ('CANCELLED', 'Storniert')], default='DRAFT', max_length=30, verbose_name='Status')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Externe Referenz')),
                ('requested_ship_date', models.DateField(blank=True, null=True, verbose_name='Gewünschtes Versanddatum')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outbound_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_orders', to='inventory.customer', verbose_name='Kunde')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_orders', to='inventory.deliveryaddress', verbose_name='Lieferadresse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OutboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Menge')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.outboundorder', verbose_name='Versandauftrag')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_order_items', to='inventory.product', verbose_name='Produkt')),
                ('transport_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_order_items', to='inventory.transportorder', verbose_name='Transportauftrag')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
